version: '2'

networks:
  BYTOM:

services:
  postgres:
    image: postgres:latest
    container_name: bu_postgres
    restart: always
    volumes:
      - ./.docker/databases/postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    depends_on:
      - nginx
    environment:
      - POSTGRES_USER=bytom
      - POSTGRES_PASSWORD=simplepassword
      - POSTGRES_DB=bytom
    networks:
      - BYTOM

  composer:
    image: composer
    container_name: bu_composer
    restart: 'no'
    working_dir: /app
    volumes:
    - ./:/app
    command: install
    networks:
    - BYTOM

  redis:
    image: redis
    container_name: bu_redis
    restart: always
    volumes:
      - ./.docker/databases/redis:/data
    ports:
      - "6379:6379"
    networks:
      - BYTOM

  phpfpm:
    build: .docker/containers/php
    container_name: bu_phpfpm
    restart: always
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    networks:
      - BYTOM

  phpcron:
    build: .docker/containers/php_cron
    container_name: bu_phpcron
    restart: always
    depends_on:
      - redis
    volumes:
      - ./:/app
    command: cron && tail -f /var/log/cron.log
    networks:
      - BYTOM

  phpworker:
    build: .docker/containers/php_worker
    container_name: bu_phpworker
    restart: always
    depends_on:
      - redis
    volumes:
      - ./:/app
    command: php /app/artisan queue:work --sleep=3 --tries=3
    networks:
      - BYTOM
